apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: ak-dev1
  labels:
    app: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: $(Parameters.containers)
        ports:
        - containerPort: 5000
