apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: smallcase-demo
  labels:
    run: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
